name: ONLY Build Docs

on:
  push:
    branches: *
  pull_request:
    branches: [ main ]

jobs:
  buildDocs:
    runs-on: ubuntu-latest

    # Note that this workflow uses the latest stable version of the Dart SDK.
    # Docker images for other release channels - like dev and beta - are also
    # available. See https://hub.docker.com/r/cirrusci/flutter for the available
    # images.
    container:
      image:  cirrusci/flutter:1.22.6

    steps:
      
      - name: Print Flutter version
        run: flutter --version
        
      - name: Checkout Repo
        uses: actions/checkout@v2
        
      - name: Install dependencies
        run: flutter pub get

      - name: Build docs
        run: dartdoc
