name: Build and Deploy Docs

on:
  push:
    branches: [ main ]

jobs:
  buildAndDeployDocs:
    runs-on: ubuntu-latest

    # Note that this workflow uses the latest stable version of the Dart SDK.
    # Docker images for other release channels - like dev and beta - are also
    # available. See https://hub.docker.com/r/cirrusci/flutter for the available
    # images.
    container:
      image:  cirrusci/flutter:1.22.6

    steps:
      
      - name: Print Flutter version
        run: which flutter
        
      - name: Checkout Repo
        uses: actions/checkout@v2
        
      - name: Install dependencies
        run: flutter pub get

      - name: Build docs
        run: dartdoc
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc/api
        
        
